version: '3.5'

services:
  address-provider:
    container_name: address_provider
    build: .
    ports:
      - 3890:80
    volumes:
      - tmp_vol:/data

volumes:
  tmp_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
